# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cec46c7ad3f6f6123f511b9c9f19fa10f33f26ff5344695f7314408ed705cd2b93bc82be749c76d8ea9db0a15eecfca70be6dc32dcf51da23ed50dd710dda5a5

test:
  secret_key_base: cf68f6bc574b9dcda3d6ac66ab2d69e1ec03b6a6efc1278a285f3abe4fa5d686c22bf496003a3a21f349d7b80407729d141c9aa800097873d4863ed2efd5edb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
